### ISSUE TITLE
Problem with screen read feature in iOS

### ISSUE THREAD

**Issue by tkacikr** [Adventech/sabbath-school-ios#110]
A friend with poor eyesight was showing me a bug in the iOS version of the app that makes it impossible to use the screen read feature (swipe two fingers down from the top of the screen). If it's on any day other than the intro, the gesture returns to the intro and everything is read from the beginning, not the current day. Haven't noticed this problem with other apps.
He has an iPhone 13 and an iPad - both with current iOS 15.5.

**Comment by VitalikL** [comment]
Thanks @tkacikr - will look into it.

**Comment by tkacikr** [comment]
My friend bought a new iPad Pro M1, and he confirmed the same problem with the screen read feature (swipe two fingers down from the top of the screen) in the Sabbath School app.

**Comment by VitalikL** [comment]
@tkacikr Fixed in the upcoming new release

**Comment by tkacikr** [comment]
Great. My friend is looking forward to the repair. He wrote me that it will help him a lot.
