### ISSUE TITLE
All Lessons Lost on Relaunch iOS 

### ISSUE THREAD

**Issue by tinachi7** [Adventech/sabbath-school-ios#116]
Of late all downloaded lessons are no longer available on relaunch of the iOS app. I have to re-download all the lessons at least 3 times a week.

**Comment by VitalikL** [comment]
What do you mean by "re-download"? Can you attach a screenshot or a video recording?

**Comment by tinachi7** [comment]
Unfortunately I can’t. But the idea is if I open a lesson using data, i should be able to see that lesson even when I’m offline right? But then that’s not how it’s working. If I open a lesson(s) when I open the app later on with phone data turned off the app gets stuck on loading.

**Comment by VitalikL** [comment]
@tinachi7 Fixed in the upcoming release
