### ISSUE TITLE
Issue with notes not saving

### ISSUE THREAD

**Issue by iRoachie** [Adventech/sabbath-school-ios#130]
Encountered an issue this morning during devotion.

It seems that notes and highlights aren’t being saved. After something as simple as going back to view all the lessons seems to delete any notes, you’ve made.

I attached a video:
https://user-images.githubusercontent.com/5962998/207841647-bb037f56-920b-40da-88a3-6e02c9db2102.mp4

iPad OS - 16.2
App Version - 3.2.6

**Comment by VitalikL** [comment]
@iRoachie I believe it was the backend issue and has been resolved. Just in case if it persists on the device, logout and relogin should solve the issue
