### ISSUE TITLE
Bible verse links are not working (iPad app)

### ISSUE THREAD

**Issue by webknows** [Adventech/sabbath-school-ios#131]
Whenever I touch a link to a Bible verse mention inside a Sabbath School text, nothing happens.

**Steps to reproduce:**
1. open up the Sabbath School app
2. select any Standard Adult lesson from the list on the first row
3. touch the 'Read' button underneath the lesson's date (or select a week's lesson from the list)
4. scroll down the text until a Bible verse mention is found (the text is underscored, indicating it is a link)
5. touch the Bible verse mention

**Expected result:**

- The mentioned Bible verse is displayed

**Current result:**

- By touching the Bible verse mention, its text is briefly highlighted and then nothing else happens

**Version information:**

- Sabbath School app version 3.2.6
- iPad Pro 11-inch (3rd generation)
- iPadOS version 16.2

**Comment by VitalikL** [comment]
@EmersonCarpes Can you please take a look at this? I can not reproduce on my real device.

**Comment by EmersonCarpes** [comment]
@VitalikLI tried to reproduce here on an iPad Air real device and in the simulator of iPad Pro both are ok.

@webknows is this happening for all bible verse or is a specific case? Could you send a video please?

**Comment by webknows** [comment]
GitHub doesn’t like the size of that file, so https://share.icloud.com/photos/003pru8WbIllJf0v3_cZz2iMg

- Reeve

**Comment by EmersonCarpes** [comment]
@webknows looks like you are using a mouse, right? If you tap directly on iPad screen the issue still happen? I tried to connect my Magic Mouse, but even this way works for me.

**Comment by webknows** [comment]
When I made the video I was using the Magic Keyboard's trackpad as input and connected to the iPad. If I remove the keyboard/trackpad, and use only my fingers to tap, I have the same result.

**Comment by altati44** [comment]
The Bible link doesn't work

**Comment by VitalikL** [comment]
@altati44 Can you please provide screen recording? This issue has been quite hard to reproduce

**Comment by altati44** [comment]
I attached a short video, you can watch when I touch the verses link
nothing happens. Thank you.

**Comment by VitalikL** [comment]
@altati44 fixed in the upcoming release
