### ISSUE TITLE
Can't build app with Apple chip

### ISSUE THREAD

**Issue by merlin-zaraza** [Adventech/sabbath-school-ios#134]
Getting next error when try to build app from sources on my M2 Air:
`/Users/vitalii/github/Adventech/sabbath-school-ios/Pods/R.swift/rswift: Bad CPU type in executable`

Seems like `R.swift` library have to be updated to support ARM executable

**Comment by VitalikL** [comment]
That is strange. It works fine on my Apple silicon (M1 MBP). Which XCode version are you using? @merlin-zaraza

**Comment by merlin-zaraza** [comment]
Xcode version is 14.3

Here is the output of `file Pods/R.swift/rswift` command:
```
Pods/R.swift/rswift: Mach-O 64-bit executable x86_64
```

And R.swift version is 5.4.0

**Comment by merlin-zaraza** [comment]
@VitalikL Just removed `Podfile.lock` file and `Pods` folder and did `pod install` again. Seems like it did it. Why `Podfile.lock` is in repo and not in ignored list?

**Comment by VitalikL** [comment]
I suspect something with the updated XCode version - I am on `14.0.1` with `5.3.0` R.swift.

Pinging @EmersonCarpes just in case.

**Comment by VitalikL** [comment]
> @VitalikL Just removed `Podfile.lock` file and `Pods` folder and did `pod install` again. Seems like it did it. Why `Podfile.lock` is in repo and not in ignored list?

I believe its needed for successful GH Actions build. Strange that it caused an issue.
