### ISSUE TITLE
The app does not have state between days

### ISSUE THREAD

**Issue by obedmacallums** [Adventech/sabbath-school-ios#163]
When I am reading and open another app (for example bible app) I loose my lecture when return to the app, if I was reading the Monday the app go back to Saturday day. That is a bad experience for the user, I hope you make something with this, correct is the app returns to the same state (including day and paragraph)

**Comment by EmersonCarpes** [comment]
Hey @obedmacallums we'll take a look on this.

**Comment by VitalikL** [comment]
@obedmacallums fixed in the upcoming release
