### ISSUE TITLE
Adding notes anywhere 

### ISSUE THREAD

**Issue by iRoachie** [Adventech/sabbath-school-ios#166]
Hey team, this is feature request.

I’d love the ability to add a note anywhere there’s text, similar to the Bible App. Right now we can select text and highlight it. It would be awesome to click add note and a pop up comes up for us to enter text.

Maybe a small icon can appear where there’s a note. Clicking it would expand to the note view.

Another option is how the “Sabbath school quarterly” app does it by allow you to add a note under every paragraph.
![IMG_0623](https://github.com/user-attachments/assets/edceb63b-b6d7-481e-80ce-41374c14a3ee)

**Comment by VitalikL** [comment]
@iRoachie We have implemented this in v3 of the API and planning release in the first quarter of 2025-01

**Comment by iRoachie** [comment]
Thanks! @VitalikL Great work
