### ISSUE TITLE
Content Missing Issue

### ISSUE THREAD

**Issue by blaiseAI** [Adventech/sabbath-school-ios#167]
It seems like the content for the content section is missing. I checked yesterday and today, and it was the same. Could you please look into why the data is missing for the content section? Only the titles are available.

This issue is on iOS

**Comment by EmersonCarpes** [comment]
Hey @blaiseAI, could you provide more details please(maybe a video)? I downloaded app from App Store and it looks fine to me.

Thanks!

**Comment by blaiseAI** [comment]
Kindly see attached video screenshot, I'm on iOS18, I'm not sure if that might contribute to this behaviour

https://github.com/user-attachments/assets/a604dc0d-05df-48c4-b69b-3fe7768617f3

**Comment by VitalikL** [comment]
@blaiseAI Did you build local version?

**Comment by blaiseAI** [comment]
> @blaiseAI Did you build local version?

Hi @VitalikL, I did not. I downloaded the app from the App Store, I also tried to uninstall the app and reinstall it, and they still see the same issue

**Comment by EmersonCarpes** [comment]
@blaiseAI, are you using the latest beta? I’m using the iOS 18 beta too, without any problems.

**Comment by blaiseAI** [comment]
> @blaiseAI, are you using the latest beta? I’m using the iOS 18 beta too, without any problems.

Yeah it's the one I'm using!

[image](https://github.com/user-attachments/assets/4d51c5bb-29fc-44d3-b44a-d018f56d5c40)

**Comment by jshim96** [comment]
Also experiencing the same {{content}} issue on both latest builds of iOS and iPadOS. Have tried to clear all downloaded content, and also have tried reinstalling from the App Store (neither resolves the issue). Currently on iOS 18.2 (22C5109p) beta, and iPadOS 18.2 (22C5125e) beta.

**Comment by VitalikL** [comment]
@blaiseAI  @jshim96 Should be fixed in the upcoming release as we move to completely native version
