### ISSUE TITLE
Baby Steps curriculum missing from iOS app

### ISSUE THREAD

**Issue by clydeugene** [Adventech/sabbath-school-ios#170]
Hi everyone,

I just happened to be on the website and noticed there’s a [Baby steps curriculum](https://sabbath-school.adventech.io/resources/en/aij/2025-00-bb-tg/02-curriculum-resources), but it is missing from the iOS app.

When I click any of the links, they redirect to the app, but there’s nothing there. I’m not sure if any of you have noticed this behavior as well.

Clyde

**Comment by VitalikL** [comment]
Hello @clydeugene . We are actually finishing the new release of the app that will include AIJ curriculum. The release will be before end of the year, so stay tuned!
