### ISSUE TITLE
Position for highlight is wrong after open the verse

### ISSUE THREAD

**Issue by tarigancana** [Adventech/sabbath-school-ios#35]
How to reproduce : 
1. Select text to highlight
2. Open a verse and then close the verse
![whatsapp image 2017-06-18 at 23 04 08](https://user-images.githubusercontent.com/11748229/27262227-963f480a-547c-11e7-8f0d-8798fc3531ca.jpeg)

**Comment by VitalikL** [comment]
@tarigancana  This should be fixed with the latest `beta`. Can you check

**Comment by VitalikL** [comment]
Fixed in the next `beta`
