### ISSUE TITLE
Height for notes is wrong after reopen the lesson

### ISSUE THREAD

**Issue by tarigancana** [Adventech/sabbath-school-ios#36]
How to reproduce : 
1. write a note on the verse, and it will add the height
2. After that close the lesson and then open again

![whatsapp image 2017-06-18 at 23 04 08 1](https://user-images.githubusercontent.com/11748229/27262299-d8a26532-547d-11e7-9da5-c0d7f9831b9b.jpeg)

![whatsapp image 2017-06-18 at 23 04 08 2](https://user-images.githubusercontent.com/11748229/27262300-d8a3e5c4-547d-11e7-99b8-f26ae9148190.jpeg)

**Comment by VitalikL** [comment]
@tarigancana This should be fixed with the latest beta. Can you double check

**Comment by VitalikL** [comment]
Fixed in the next `beta`
