### ISSUE TITLE
Link in About page doesn’t work

### ISSUE THREAD

**Issue by Abishai2007** [Adventech/sabbath-school-ios#50]
![a2eaa4e2-597e-4a2d-9987-c00952291eef](https://user-images.githubusercontent.com/17181837/33302935-cd2b5f32-d453-11e7-82e1-0933ca33c001.png)

**Comment by tarigancana** [comment]
Seems dns for www.adventech.io is not configure properly as the web can be open with http://adventech.io

@VitalikL

**Comment by Abishai2007** [comment]
You’re correct. The problem is trying to resolve www.adventech.io from the app.

**Comment by VitalikL** [comment]
Should be fixed in the upcoming iOS version + I have added `www` just now, so should be also fixed in current released version
