### ISSUE TITLE
READ / OPEN are not localized properly

### ISSUE THREAD

**Issue by shinjoe** [Adventech/sabbath-school-ios#64]
Hey @VitalikL, I noticed that you have localized strings for "Read" and "Open". 

However, they don't seem to be working. Try changing the language to anything other than English -- it'll still read "READ" and "OPEN". If this is intentional, then feel free to close this ticket. 

I'm assuming it's not intentional though, since you have localized strings for them. 

Took a quick look at the code, and it looks like the culprit might be the uppercasing:
`"Open".localized().uppercased()`

I have a hunch that the localization will work if we removed the uppercase and did:

`"Open".localized()`. If I were to venture a guess, perhaps its because some languages (like Korean) don't really have a notion of uppercase characters, so Swift is just defaulting to the non-localized, English versions?

In any case, if that's true, feel free to confirm. I'll then send in a pull request with the fixes.

**Comment by VitalikL** [comment]
Hi @shinjoe did you change the language of the lesson or the language of the system in iOS?

**Comment by shinjoe** [comment]
I changed it in the lesson app. I see other strings get properly localized,
which is why I figured that this might be a bug.

**Comment by VitalikL** [comment]
Interesting..which other strings do you mean? Like lesson title and content?

**Comment by shinjoe** [comment]
Yep, exactly.

**Comment by VitalikL** [comment]
In this case it is ok. The UI (buttons, controls & etc) are part of app
localization and only translated when user interface changes

**Comment by shinjoe** [comment]
All right, thanks for clarifying. In that case, I'll close this.
