### ISSUE TITLE
Text disappears when highlighted

### ISSUE THREAD

**Issue by carlbrugger** [Adventech/sabbath-school-ios#71]
I've run into an issue where after I highlight a section of text that section of text disappears. The text will reappear after I go to the lesson list page and back to the lesson I was reading. This issue appears to happen when highlighting text (anything but the first sentence) beneath a notes section.

https://www.dropbox.com/s/ix183tj5d0inva6/ScreenRecording_10-31-2018%2011-55-28.mp4?dl=0
https://www.dropbox.com/s/mecofft2djfqmow/ScreenRecording_10-31-2018%2011-50-51.mp4?dl=0

**Comment by VitalikL** [comment]
@carlbrugger I know that this issue is quite old. It might have already been fixed, indirectly, because I can not reproduce this anymore

**Comment by carlbrugger** [comment]
@VitalikL I haven't seen the issue recently either. Thanks.
