### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by danielbair** [Adventech/sabbath-school-ios#78]
This workspace has projects that contain source code developed with Swift 3.x. This version of Xcode (11.0) does not support building or migrating Swift 3.x targets.

Use Xcode 10.1 to migrate the code to Swift 4.

**Comment by abrampers** [comment]
Yes, I'm experiencing this Issue. Currently trying to migrate the swift versions.

**Comment by VitalikL** [comment]
The codebase has been updated to the latest Swift
