### ISSUE TITLE
iPad bug with recommend share sheet

### ISSUE THREAD

**Issue by iRoachie** [Adventech/sabbath-school-ios#79]
There’s a bug on iPad when selecting the “Recommend Sabbath School”. Attached a screenshot for reference.

 
![F0E7FD47-FAE3-42FA-9D18-B2BA46072F26](https://user-images.githubusercontent.com/5962998/66702743-f6d8b880-ecd8-11e9-9392-12cd1a574548.png)

iPad Pro 10.5 
iOS 13.1.2

**Comment by VitalikL** [comment]
FIxed now
