### ISSUE TITLE
Please add a built-in dictionary lookup option

### ISSUE THREAD

**Issue by justinlee0516** [Adventech/sabbath-school-ios#82]
We can look up a word in Bible view, but not in the main text.
It would be very helpful if we can look up a word in the ios built-in dictionary.
If everyone is busy, I can help with this as an ios developer.

Please see the "Look Up" menu in the screenshot attached. I really want that menu in the main text.

![15797038-77B0-46C1-AA16-1270C58BA22F_1_105_c](https://user-images.githubusercontent.com/20188522/82874798-d6185700-9f79-11ea-9bf0-7b3bfff19925.jpeg)

**Comment by VitalikL** [comment]
Implemented and will be available with the next release
