### ISSUE TITLE
Build failed - Fabric credentials

### ISSUE THREAD

**Issue by hreimer** [Adventech/sabbath-school-ios#83]
Hi,
when trying to build the project in XCode 11.3.1 / macOS 10.14.6 to test in the simulator I get a Build failed error because the Fabric credential files, Fabric.buildSecret and Fabric.apiKey to be exact, are not checked in, for obvious reasons.

How should I proceed to start this project? Is it possible to build and test without these credentials and if yes how? Fabric has now become Firebase or part of it, should I wait for an update for this framework?

Thanks!

**Comment by VitalikL** [comment]
Hi @hreimer 

We are not working on restructuring the codebase to be OSS friendly. Stay tuned

**Comment by hreimer** [comment]
Thanks @VitalikL, are there any updates in the meantime? (I am guessing you meant you are "now" working on it). Looking forward to trying it out!

**Comment by VitalikL** [comment]
@hreimer I am planning to push changes this week, thanks for your patience :)

**Comment by VitalikL** [comment]
@hreimer We have now deprecated Fabric and using Crashlytics pod from Firebase. I have uploaded the latest code, can you please try it now.
