### ISSUE TITLE
Wrong date is displayed in the title section

### ISSUE THREAD

**Issue by justinlee0516** [Adventech/sabbath-school-ios#84]
If I build the latest source code, I see a wrong date (the previous date) is displayed in the title section.

**Comment by VitalikL** [comment]
@justinlee0516 I can not reproduce it with the latest codebase. Can you double check now?

**Comment by miking7** [comment]
These same symptoms have now appeared on my phone - in the official app-store version. 
Notes that may be helpful: 
* the bug has only just exhibited itself very recently - ie when I opened the app two days ago, I  saw the new app icon, received the notification that the app is now officially part of the GC family, and now all the dates are wrong.
Could this bug be somehow timezone-related? (I'm using the app from Australia, and although the dates shown in the title area are wrong, they do line up with what the dates would be in the US!
* I've uploaded a screenshot showing the first day of this current week's lesson. This should be showing "Sabbath, May 22", but is showing "Friday, May 21". 
* Note also that when I tap the "read" button to open "today's" lesson, it is correctly taking me to the lesson for today (which right now is Sunday May 23), but is displaying the title as "Saturday, May 22". 
[image](https://user-images.githubusercontent.com/5072816/119241592-ef5ae000-bb9a-11eb-9998-f0cefef6351c.png))

**Comment by alexgreendesign** [comment]
I'm seeing the same thing - the correct date was being shown on the older version, however after updating to the latest version I'm now seeing yesterdays date in the title section (I'm also in Australia).

**Comment by VitalikL** [comment]
@miking7 @alexgreendesign I can confirm I can reproduce the issue with the Australian timezone. Will fix

**Comment by VitalikL** [comment]
Fixed, will be available in the next release
