### ISSUE TITLE
❌  Project doesn't compile on Xcode 12

### ISSUE THREAD

**Issue by Senocico** [Adventech/sabbath-school-ios#86]
I tried to run the project on the latest Xcode version, but it doesn't work, the compiler reports more than 130 build errors. 
Especially seems that the **pod 'Texture'** has suffered some important changes, so the code should be updated, because from `'Texture', '>= 2.0'` this framework has undergone many changes.

Can you help us with this update?
Thanks a lot for your support 🙏🏻

**Comment by VitalikL** [comment]
@Senocico The latest codebase with upgraded pods has been pushed.

**Comment by Senocico** [comment]
@VitalikL Thank you very much for your support!
God bless you! 🙏
