### ISSUE TITLE
Language Issues / Improvements

### ISSUE THREAD

**Issue by davidskau** [Adventech/sabbath-school-ios#92]
Even when setting the app in Spanish, the date/day of the week display on each’s day’s lesson remains 
![1BBC3C20-5EB0-47B7-B86D-C5AB42D1FEA5](https://user-images.githubusercontent.com/13891351/149633707-e0c78212-e415-49ed-8e41-6ba3f50881d1.jpeg)
in English.

**Comment by davidskau** [comment]
Minor: Spanish text rendering missing spaces at poetic line breaks (ie, Psalms) 
![D249EC8C-898F-41DD-AA20-E94FC9954148](https://user-images.githubusercontent.com/13891351/149633847-b35636f6-c3ce-446d-877a-8a357d163b3c.jpeg)

**Comment by davidskau** [comment]
Suggestion: Fast language switching / remember place when switching languages.

Currently switching languages takes one back to the main menu to navigate to a week and day. For bilingual users it would be more helpful for language to be included in the “text size” menu, and for switching language to display the same day as was being viewed previously, just in the other language.

**Comment by VitalikL** [comment]
Thanks for the feedback @davidskau . Regarding the date displayed this is part of the native app interface and follows the current's user locale setting, which is recommended when dealing with multilingual content in a multilingual environment. 

In terms of the suggestion of changing the language contextually while reading the lesson I think its a good idea and we will definitely consider adding and working on it.
