### ISSUE TITLE
Offline capabilities broken

### ISSUE THREAD

**Issue by miking7** [Adventech/sabbath-school-ios#95]
Since the most recent app store update, the offline capabilities that made this such a wonderful app seem to be broken. It used to be that once you had opened a particular week's study, and the text and banner image had loaded, that the app would function perfectly with no internet connection. This was a very important feature not only for people without a permanent internet connection who might need for example to download content before going to church, but also for the many people who switch their phone to airplane mode when when studying the Bible to remove distractions and to prevent interruptions during their time with God. 
Let me know if you need further details or any screenshots to be able to diagnose this issue.

**Comment by VitalikL** [comment]
@miking7 Current app store has the bug which affects the offline capability. We have already fixed it and it should be released soon.

**Comment by VitalikL** [comment]
@miking7 The release has been approved - please update to the latest version
